### ISSUE TITLE
Просмотр задания WYSIWIG

### ISSUE THREAD

**Issue by eugeniuznagovan** [eugeniuznagovan/WYSIWYG#1]
Привет @xanf  !
Пожалуйста посмотрите задание 😃

**Comment by xanf** [comment]
@JSMonk

**Comment by JSMonk** [comment]
Здравствуйте, Евгений.
Стили не сохраняются при компировании в Microsoft Office Online:

<img width="175" alt="Screen Shot 2021-02-08 at 2 30 38 PM" src="https://user-images.githubusercontent.com/10776615/107219910-63251280-6a1a-11eb-897b-9bf618d46455.png">
<img width="508" alt="Screen Shot 2021-02-08 at 2 30 31 PM" src="https://user-images.githubusercontent.com/10776615/107219916-63bda900-6a1a-11eb-9956-b3d4066793e5.png">

К сожалению, вчера был последний день сдачи, и даже если Вы поправите, мы не сможем зачислить Вас на курс. Но, если Вам интересно, Вы можете попробовать дофиксить Ваше решение и мы обязательно его проверим :)
В любом случае, спасибо Вам большое за участие и будем Вас ждать на наших следующих курсах ^_^

**Comment by eugeniuznagovan** [comment]
@JSMonk Спасибо за feedback. Очень печально :(
